import Spline from '@splinetool/react-spline';
import { Rocket, Sparkles } from 'lucide-react';

export default function Hero3D() {
  return (
    <section className="relative h-[60vh] w-full overflow-hidden bg-gradient-to-b from-[#0b0b14] via-[#0f0f1f] to-[#0b0b14]">
      <div className="absolute inset-0">
        <Spline
          scene="https://prod.spline.design/EF7JOSsHLk16Tlw9/scene.splinecode"
          style={{ width: '100%', height: '100%' }}
        />
      </div>

      {/* soft glow overlay that doesn't block interaction */}
      <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(ellipse_at_center,rgba(124,58,237,0.25),rgba(0,0,0,0.4))]" />

      <div className="relative z-10 mx-auto flex h-full max-w-6xl flex-col items-start justify-center px-6 text-white">
        <div className="inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-1 backdrop-blur">
          <Sparkles className="h-4 w-4 text-violet-300" />
          <span className="text-xs uppercase tracking-wider text-violet-200">AI + Mermaid</span>
        </div>
        <h1 className="mt-4 text-4xl font-semibold leading-tight md:text-6xl">
          Type your idea. Get a diagram.
        </h1>
        <p className="mt-3 max-w-2xl text-sm text-zinc-300 md:text-base">
          Flowcharts, ERD, Class, Sequence and more — generated by AI and rendered in real-time with Mermaid.
        </p>
        <div className="mt-6 inline-flex items-center gap-3 rounded-lg bg-white/10 px-4 py-2 text-sm text-zinc-200 backdrop-blur">
          <Rocket className="h-4 w-4 text-violet-300" />
          <span>Futuristic, fast, and frictionless.</span>
        </div>
      </div>
    </section>
  );
}
